baseurl = "/"
languageCode = "en-us"
title = "eltimn"

[pagination]
  pagerSize = 10

[params]
  disqusShortname = "eltimn"
  Description = "The home of Tim Nelson"
  SelfIntro = "I'm Tim, a software developer. Currently focused on NixOS, Go, Kotlin, and HTMX."
  GithubID = "eltimn"
  TwitterID = "eltimn"

[menu]
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
